name: Build macOS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v6

      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set release version
        run: node scripts/sync-version.js "${{ inputs.version }}"

      - name: Build app
        env:
          VITE_KLIPY_API_BASE_URL: ${{ vars.VITE_KLIPY_API_BASE_URL }}
          VITE_KLIPY_PER_PAGE_LIMIT: ${{ vars.VITE_KLIPY_PER_PAGE_LIMIT }}
          VITE_KLIPY_API_KEY: ${{ secrets.VITE_KLIPY_API_KEY }}
        run: pnpm tauri build --bundles dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: mexboard-macos
          path: src-tauri/target/release/bundle/dmg/*.dmg
          if-no-files-found: error
